version: '1.0'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: ontology-mongo
    restart: always
    logging:
      options:
        max-size: 500mb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo